// Canonical story chapters — verbatim EN/UK/ES from the original artifact.
// World ids: pirates | space | dollhouse ("computer" in the content file = "space" here).
const T = (en, uk, es) => ({ en, uk, es });

export const ARCS = {
  pirates: {
    title: T("The Treasure Map", "Карта скарбів", "El mapa del tesoro"),
    subtitle: T("Treasure hunt", "Пошуки скарбу", "Búsqueda del tesoro"),
    desc: T(
      "Unfold a mysterious map, sail through all ten landmarks, and collect programs on the way to the greatest treasure.",
      "Розгорни таємничу карту, пройди морем усі десять позначок і збирай програми на шляху до найбільшого скарбу.",
      "Despliega un mapa misterioso, navega por sus diez lugares y reúne programas camino al mayor tesoro."
    ),
    drop: T("treasure chest", "скриня зі скарбом", "cofre del tesoro"),
  },
  space: {
    title: T("Starship Rescue", "Порятунок зорельота", "Rescate de la nave estelar"),
    subtitle: T("Starship repair", "Ремонт зорельота", "Reparación de la nave"),
    desc: T(
      "Your starship broke down far from Earth. Earn volts, repair one vital system at every level, and bring the crew home.",
      "Твій зореліт зламався далеко від Землі. Заробляй вольти, ремонтуй по одній важливій системі на кожному рівні й поверни екіпаж додому.",
      "Tu nave se averió lejos de la Tierra. Gana voltios, repara un sistema vital en cada nivel y lleva a la tripulación a casa."
    ),
    drop: T("parts crate", "контейнер із деталями", "caja de repuestos"),
  },
  dollhouse: {
    title: T("The Empty Dollhouse", "Порожній ляльковий будинок", "La casa de muñecas vacía"),
    subtitle: T("House restoration", "Відновлення будинку", "Restauración de la casa"),
    desc: T(
      "A beautiful house was given to you completely empty. Repair one space at every level and turn it into a real home.",
      "Тобі подарували чудовий, але зовсім порожній будинок. На кожному рівні ремонтуй новий простір і перетвори його на справжній дім.",
      "Te regalaron una casa preciosa, pero completamente vacía. Repara un espacio en cada nivel y conviértela en un verdadero hogar."
    ),
    drop: T("renovation box", "коробка для ремонту", "caja de renovación"),
  },
};

// (title, scene, mission, unlock) × EN/UK/ES
const C = (tEn, tUk, tEs, sEn, sUk, sEs, mEn, mUk, mEs, uEn, uUk, uEs) => ({
  title: T(tEn, tUk, tEs),
  scene: T(sEn, sUk, sEs),
  mission: T(mEn, mUk, mEs),
  unlock: T(uEn, uUk, uEs),
});

export const CHAPTERS = {
  pirates: [
    C("The Sealed Map", "Запечатана карта", "El mapa sellado",
      "A bottle washes ashore with a map folded inside. Ten faded landmarks lead to a treasure no captain has ever reached.",
      "Хвиля виносить на берег пляшку зі складеною всередині картою. Десять вицвілих позначок ведуть до скарбу, якого не знаходив жоден капітан.",
      "Una botella llega a la orilla con un mapa doblado dentro. Diez lugares descoloridos llevan a un tesoro que ningún capitán ha alcanzado.",
      "Earn EXP to open the map and prepare your ship.",
      "Зароби EXP, щоб відкрити карту й підготувати корабель.",
      "Gana EXP para desbloquear el mapa y preparar la nave.",
      "Map opened · Harbor route revealed",
      "Карту відкрито · Шлях із гавані знайдено",
      "Mapa abierto · Ruta del puerto revelada"),
    C("The First Map Piece", "Перша частина карти", "La primera pieza del mapa",
      "The harbor mark glows. Your crew raises the sails and follows the first dotted line toward Coconut Key.",
      "Позначка гавані засвітилася. Команда підіймає вітрила й рушає пунктирним шляхом до Кокосового острова.",
      "La marca del puerto brilla. La tripulación iza las velas y sigue la primera línea de puntos hacia Cayo Coco.",
      "Complete quests to reach the first island.",
      "Виконуй квести, щоб дістатися першого острова.",
      "Completa misiones para llegar a la primera isla.",
      "Coconut Key · First program cache",
      "Кокосовий острів · Перший запас програм",
      "Cayo Coco · Primer alijo de programas"),
    C("The Whispering Reef", "Шепітливий риф", "El arrecife susurrante",
      "A torn map piece is trapped beyond a reef of blue lights. A steady captain can find the safe channel.",
      "За рифом синіх вогнів застрягла відірвана частина карти. Уважний капітан зможе знайти безпечний прохід.",
      "Una pieza rota del mapa está atrapada tras un arrecife de luces azules. Un capitán firme puede encontrar el paso seguro.",
      "Build EXP to navigate the reef.",
      "Накопичуй EXP, щоб пройти крізь риф.",
      "Acumula EXP para atravesar el arrecife.",
      "Reef passage · Second map piece",
      "Прохід крізь риф · Друга частина карти",
      "Paso del arrecife · Segunda pieza del mapa"),
    C("Storm over Coin Bay", "Буря над Монетною затокою", "Tormenta sobre Bahía Moneda",
      "A storm hides the next landmark. Every finished quest brightens the lantern and reveals another inch of the route.",
      "Буря ховає наступну позначку. Кожен завершений квест робить ліхтар яскравішим і відкриває ще частину маршруту.",
      "Una tormenta oculta el siguiente lugar. Cada misión terminada aviva el farol y revela otro tramo de la ruta.",
      "Power the storm lantern with EXP.",
      "Заряди штормовий ліхтар досвідом EXP.",
      "Enciende el farol de tormenta con EXP.",
      "Coin Bay · Storm program cache",
      "Монетна затока · Запас штормових програм",
      "Bahía Moneda · Alijo de programas de tormenta"),
    C("The Hidden Lagoon", "Прихована лагуна", "La laguna oculta",
      "Behind a curtain of mist waits a lagoon filled with clues, program capsules, and the missing center of the map.",
      "За завісою туману чекає лагуна з підказками, капсулами програм та загубленою серединою карти.",
      "Tras una cortina de niebla espera una laguna con pistas, cápsulas de programas y el centro perdido del mapa.",
      "Follow the clues across the lagoon.",
      "Іди за підказками через лагуну.",
      "Sigue las pistas por la laguna.",
      "Hidden Lagoon · Center map piece",
      "Прихована лагуна · Центральна частина карти",
      "Laguna oculta · Pieza central del mapa"),
    C("The Compass Trial", "Випробування компаса", "La prueba de la brújula",
      "The restored map points in two directions at once. Only a captain trusted by the crew can wake the true compass.",
      "Відновлена карта вказує одразу в два боки. Лише капітан, якому довіряє команда, може пробудити справжній компас.",
      "El mapa restaurado apunta en dos direcciones a la vez. Solo un capitán en quien confíe la tripulación puede despertar la brújula verdadera.",
      "Lead the crew through harder family quests.",
      "Веди команду через складніші сімейні квести.",
      "Guía a la tripulación en misiones familiares más difíciles.",
      "True compass · Captain's program",
      "Справжній компас · Програма капітана",
      "Brújula verdadera · Programa del capitán"),
    C("The Moonlit Caves", "Печери місячного сяйва", "Las cuevas iluminadas por la luna",
      "At midnight, the compass reveals caves that disappear at sunrise. Their walls hold the final island coordinates.",
      "Опівночі компас показує печери, що зникають на світанку. На їхніх стінах заховані останні координати острова.",
      "A medianoche, la brújula revela cuevas que desaparecen al amanecer. Sus paredes guardan las coordenadas finales de la isla.",
      "Reach the caves before the moon sets.",
      "Дістанься печер до заходу місяця.",
      "Llega a las cuevas antes de que se oculte la luna.",
      "Moonlit Caves · Island coordinates",
      "Місячні печери · Координати острова",
      "Cuevas lunares · Coordenadas de la isla"),
    C("The Vault beneath the Waves", "Сховище під хвилями", "La cámara bajo las olas",
      "A stone vault under the sea guards the key to Treasure Isle and a cache of rare programs.",
      "Кам'яне сховище під морем береже ключ від Острова скарбів і сховище рідкісних програм.",
      "Una bóveda de piedra bajo el mar guarda la llave de la Isla del Tesoro y un alijo de programas raros.",
      "Earn the vault key through quests.",
      "Зароби ключ від сховища, виконуючи квести.",
      "Consigue la llave de la bóveda con misiones.",
      "Ocean vault · Treasure key",
      "Підводне сховище · Ключ до скарбу",
      "Bóveda submarina · Llave del tesoro"),
    C("Race to Treasure Isle", "Перегони до Острова скарбів", "Carrera a la Isla del Tesoro",
      "The whole map is visible now. Treasure Isle rises beyond the horizon, but the tide is already turning.",
      "Тепер видно всю карту. Острів скарбів піднімається за горизонтом, але приплив уже змінюється.",
      "Ahora se ve el mapa completo. La Isla del Tesoro surge tras el horizonte, pero la marea ya está cambiando.",
      "Fill the final voyage bar and reach the island.",
      "Заповни останню шкалу подорожі й дістанься острова.",
      "Llena la última barra del viaje y llega a la isla.",
      "Treasure Isle · Final program cache",
      "Острів скарбів · Останній запас програм",
      "Isla del Tesoro · Último alijo de programas"),
    C("The Greatest Treasure", "Найбільший скарб", "El mayor tesoro",
      "The key turns and the legendary chest opens. The treasure marks every challenge your crew conquered together.",
      "Ключ повертається, і легендарна скриня відчиняється. Скарб нагадує про кожне випробування, яке команда здолала разом.",
      "La llave gira y el cofre legendario se abre. El tesoro recuerda cada desafío que la tripulación superó unida.",
      "Celebrate the completed map as a Family Legend.",
      "Відсвяткуй завершену карту як Сімейна легенда.",
      "Celebra el mapa completo como Leyenda familiar.",
      "Legendary treasure · Complete map",
      "Легендарний скарб · Повна карта",
      "Tesoro legendario · Mapa completo"),
  ],

  space: [
    C("Emergency in Deep Space", "Аварія у далекому космосі", "Emergencia en el espacio profundo",
      "Mid-flight, the starship shudders and every screen goes dark. Ten vital systems are damaged, and Earth is far behind you.",
      "Посеред польоту зореліт здригається, і всі екрани гаснуть. Десять важливих систем пошкоджено, а Земля далеко позаду.",
      "En pleno vuelo, la nave se sacude y todas las pantallas se apagan. Diez sistemas vitales están dañados y la Tierra queda muy lejos.",
      "Earn EXP to restart the emergency battery.",
      "Зароби EXP, щоб перезапустити аварійну батарею.",
      "Gana EXP para reiniciar la batería de emergencia.",
      "Emergency battery · Lights and diagnostics",
      "Аварійна батарея · Світло й діагностика",
      "Batería de emergencia · Luces y diagnóstico"),
    C("Communications Array", "Система зв'язку", "Sistema de comunicaciones",
      "Emergency power is back, but Earth cannot hear you. The communications array must be rebuilt piece by piece.",
      "Аварійне живлення повернулося, але Земля тебе не чує. Систему зв'язку треба відбудувати деталь за деталлю.",
      "La energía de emergencia ha vuelto, pero la Tierra no puede oírte. Hay que reconstruir el sistema de comunicaciones pieza a pieza.",
      "Repair the transmitter and send a distress signal.",
      "Відремонтуй передавач і надішли сигнал лиха.",
      "Repara el transmisor y envía una señal de auxilio.",
      "Communications · Messages to Earth",
      "Зв'язок · Повідомлення на Землю",
      "Comunicaciones · Mensajes a la Tierra"),
    C("Oxygen Recycler", "Переробник кисню", "Reciclador de oxígeno",
      "The reply from Earth arrives: stay calm and repair life support next. The air gauge is slowly falling.",
      "Із Землі приходить відповідь: зберігай спокій і наступною ремонтуй систему життєзабезпечення. Рівень повітря повільно падає.",
      "Llega la respuesta de la Tierra: mantén la calma y repara ahora el soporte vital. El indicador de aire baja lentamente.",
      "Restore clean air for the crew.",
      "Віднови чисте повітря для екіпажу.",
      "Restaura el aire limpio para la tripulación.",
      "Life support · Fresh-air reserve",
      "Життєзабезпечення · Запас чистого повітря",
      "Soporte vital · Reserva de aire limpio"),
    C("Navigation Computer", "Навігаційний комп'ютер", "Computadora de navegación",
      "The crew is safe, but the route home is scrambled. Burned navigation boards show only a maze of broken stars.",
      "Екіпаж у безпеці, але маршрут додому пошкоджено. Згорілі навігаційні плати показують лише лабіринт розбитих зірок.",
      "La tripulación está a salvo, pero la ruta a casa está dañada. Las placas quemadas solo muestran un laberinto de estrellas rotas.",
      "Rebuild the navigation computer with EXP.",
      "Віднови навігаційний комп'ютер за допомогою EXP.",
      "Reconstruye la computadora de navegación con EXP.",
      "Navigation · Route home calculated",
      "Навігація · Маршрут додому розраховано",
      "Navegación · Ruta a casa calculada"),
    C("Thermal Shield", "Тепловий щит", "Escudo térmico",
      "The new route crosses a field of solar heat. Repair modules lock into the hull and begin protecting the ship.",
      "Новий маршрут проходить крізь поле сонячного жару. Ремонтні модулі стають на місце в корпусі й починають захищати корабель.",
      "La nueva ruta cruza un campo de calor solar. Los módulos de reparación encajan en el casco y empiezan a proteger la nave.",
      "Seal the thermal shield before the crossing.",
      "Заверши тепловий щит до початку переходу.",
      "Sella el escudo térmico antes de cruzar.",
      "Thermal shield · Safe solar passage",
      "Тепловий щит · Безпечний прохід біля Сонця",
      "Escudo térmico · Paso solar seguro"),
    C("Solar Wings", "Сонячні крила", "Alas solares",
      "The batteries cannot power the long journey alone. Two folded solar wings must open and catch the light.",
      "Самих батарей не вистачить на довгу подорож. Два складені сонячні крила мають розкритися й упіймати світло.",
      "Las baterías no bastan para el largo viaje. Dos alas solares plegadas deben abrirse y atrapar la luz.",
      "Charge the wing controls with volts and EXP.",
      "Заряди керування крилами вольтами й EXP.",
      "Carga los controles de las alas con voltios y EXP.",
      "Solar wings · Renewable ship power",
      "Сонячні крила · Відновлювана енергія корабля",
      "Alas solares · Energía renovable para la nave"),
    C("Maneuvering Thrusters", "Маневрові двигуни", "Propulsores de maniobra",
      "An asteroid belt blocks the route. The small thrusters that steer the ship are still offline.",
      "Пояс астероїдів перекриває шлях. Малі двигуни, що керують кораблем, досі не працюють.",
      "Un cinturón de asteroides bloquea la ruta. Los pequeños propulsores que dirigen la nave siguen apagados.",
      "Repair precision steering for the asteroid run.",
      "Відремонтуй точне керування для проходу крізь астероїди.",
      "Repara el control preciso para atravesar los asteroides.",
      "Thrusters · Asteroid steering",
      "Маневрові двигуни · Керування серед астероїдів",
      "Propulsores · Control entre asteroides"),
    C("Main Engine", "Головний двигун", "Motor principal",
      "Earth appears on the repaired map, but the main engine cannot start. This is the biggest repair yet.",
      "Земля з'являється на відновленій карті, але головний двигун не запускається. Це найбільший ремонт досі.",
      "La Tierra aparece en el mapa reparado, pero el motor principal no arranca. Es la mayor reparación hasta ahora.",
      "Assemble the engine modules and ignite the drive.",
      "Збери модулі двигуна й запусти тягу.",
      "Monta los módulos del motor y enciende el impulso.",
      "Main engine · Homeward acceleration",
      "Головний двигун · Прискорення до дому",
      "Motor principal · Aceleración hacia casa"),
    C("Landing Guidance", "Система посадки", "Sistema de aterrizaje",
      "The ship reaches Earth orbit. One final damaged computer must guide the crew through the atmosphere.",
      "Корабель досягає орбіти Землі. Останній пошкоджений комп'ютер має провести екіпаж крізь атмосферу.",
      "La nave alcanza la órbita terrestre. Una última computadora dañada debe guiar a la tripulación por la atmósfera.",
      "Restore landing guidance and choose a safe path.",
      "Віднови систему посадки й обери безпечний шлях.",
      "Restaura el sistema de aterrizaje y elige una ruta segura.",
      "Landing guidance · Safe return corridor",
      "Система посадки · Безпечний коридор повернення",
      "Aterrizaje · Corredor seguro de regreso"),
    C("Re-entry Stabilizers", "Стабілізатори входу в атмосферу", "Estabilizadores de reentrada",
      "Earth fills the window, but the damaged stabilizers cannot hold the ship steady. Repairing this tenth and final system opens the safe way through the atmosphere.",
      "Земля заповнює ілюмінатор, але пошкоджені стабілізатори не втримують корабель рівно. Ремонт цієї десятої й останньої системи відкриє безпечний шлях крізь атмосферу.",
      "La Tierra llena la ventana, pero los estabilizadores dañados no mantienen firme la nave. Reparar este décimo y último sistema abre un camino seguro por la atmósfera.",
      "Repair the stabilizers and complete the return as a Family Legend.",
      "Відремонтуй стабілізатори й заверши повернення як Сімейна легенда.",
      "Repara los estabilizadores y completa el regreso como Leyenda familiar.",
      "Re-entry stabilizers · Crew returned home",
      "Стабілізатори входу · Екіпаж повернувся додому",
      "Estabilizadores de reentrada · Tripulación en casa"),
  ],

  dollhouse: [
    C("A House with Empty Rooms", "Будинок із порожніми кімнатами", "Una casa con habitaciones vacías",
      "A beautiful dollhouse arrives as a gift, but inside there are bare walls, dusty floors, and not a single chair.",
      "У подарунок приходить чудовий ляльковий будинок, але всередині голі стіни, запилена підлога й жодного стільця.",
      "Llega de regalo una preciosa casa de muñecas, pero dentro hay paredes desnudas, suelos polvorientos y ni una sola silla.",
      "Earn EXP to clean the entrance and make a plan.",
      "Зароби EXP, щоб прибрати вхід і скласти план.",
      "Gana EXP para limpiar la entrada y hacer un plan.",
      "Front hall · Restoration plan",
      "Передпокій · План відновлення",
      "Entrada · Plan de restauración"),
    C("The Cozy Kitchen", "Затишна кухня", "La cocina acogedora",
      "The first empty room becomes a kitchen. New floors, a tiny stove, and a table make it feel warm at last.",
      "Перша порожня кімната стає кухнею. Нова підлога, маленька плита й стіл нарешті наповнюють її теплом.",
      "La primera habitación vacía se convierte en cocina. El suelo nuevo, una pequeña estufa y una mesa por fin le dan calidez.",
      "Repair and furnish the kitchen.",
      "Відремонтуй і облаштуй кухню.",
      "Repara y amuebla la cocina.",
      "Kitchen · Stove and family table",
      "Кухня · Плита й сімейний стіл",
      "Cocina · Estufa y mesa familiar"),
    C("The Bright Living Room", "Світла вітальня", "La sala luminosa",
      "Sunlight reaches a room with peeling wallpaper. It needs color, a lamp, and a place for everyone to sit.",
      "Сонячне світло потрапляє до кімнати з обдертими шпалерами. Їй потрібні колір, лампа й місце, де всі зможуть сісти.",
      "La luz llega a una habitación con el papel despegado. Necesita color, una lámpara y un lugar donde todos puedan sentarse.",
      "Restore the living room with EXP.",
      "Віднови вітальню за допомогою EXP.",
      "Restaura la sala con EXP.",
      "Living room · Sofa and reading lamp",
      "Вітальня · Диван і лампа для читання",
      "Sala · Sofá y lámpara de lectura"),
    C("Garden behind the Wall", "Сад за стіною", "El jardín tras la pared",
      "Behind the old wallpaper is a hidden door to an overgrown garden. The house suddenly has space to breathe.",
      "За старими шпалерами — потаємні двері до зарослого саду. У будинку раптом стало легше дихати.",
      "Detrás del viejo papel tapiz hay una puerta oculta a un jardín descuidado. La casa de repente respira mejor.",
      "Clear the path and bring the garden back.",
      "Розчисти стежку й поверни сад до життя.",
      "Despeja el sendero y devuelve la vida al jardín.",
      "Garden · Outdoor family space",
      "Сад · Сімейний простір надворі",
      "Jardín · Espacio familiar al aire libre"),
    C("The Creative Workshop", "Творча майстерня", "El taller creativo",
      "An unused room is perfect for making things. Shelves, a worktable, and bright storage turn it into a workshop.",
      "Порожня кімната ідеально підходить для творчості. Полиці, робочий стіл і яскраві шафки перетворюють її на майстерню.",
      "Una habitación sin usar es perfecta para crear. Estantes, una mesa de trabajo y almacenaje de colores la convierten en taller.",
      "Build and furnish the creative room.",
      "Відремонтуй і облаштуй творчу кімнату.",
      "Construye y amuebla la sala creativa.",
      "Workshop · Space for projects",
      "Майстерня · Місце для проєктів",
      "Taller · Espacio para proyectos"),
    C("The Upstairs Bedroom", "Спальня нагорі", "El dormitorio de arriba",
      "The staircase is repaired, revealing an empty bedroom under the roof. It is ready for a bed and personal touches.",
      "Сходи відремонтовано, і під дахом відкривається порожня спальня. Вона готова до ліжка й особливих деталей.",
      "La escalera reparada revela un dormitorio vacío bajo el techo. Está listo para una cama y detalles personales.",
      "Make the upstairs bedroom cozy.",
      "Зроби спальню нагорі затишною.",
      "Haz acogedor el dormitorio de arriba.",
      "Bedroom · Rest and recharge",
      "Спальня · Відпочинок і нові сили",
      "Dormitorio · Descanso y energía"),
    C("The Playroom", "Ігрова кімната", "La sala de juegos",
      "A narrow attic opens into a surprising room. Games and soft cushions can make it the happiest place in the house.",
      "Вузьке горище веде до несподіваної кімнати. Ігри й м'які подушки можуть зробити її найвеселішим місцем у будинку.",
      "Un ático estrecho se abre a una habitación sorprendente. Juegos y cojines pueden convertirla en el lugar más alegre de la casa.",
      "Repair and furnish the playroom.",
      "Відремонтуй і облаштуй ігрову кімнату.",
      "Repara y amuebla la sala de juegos.",
      "Playroom · Family game space",
      "Ігрова кімната · Місце для сімейних ігор",
      "Sala de juegos · Espacio para jugar en familia"),
    C("The Clockwork Study", "Кабінет із годинниковим механізмом", "El estudio de engranajes",
      "A hidden study has a broken clock and walls of empty shelves. Fixing it gives the whole house a steady rhythm.",
      "У прихованому кабінеті зламаний годинник і порожні полиці. Його ремонт повертає всьому будинку рівний ритм.",
      "Un estudio oculto tiene un reloj roto y paredes de estantes vacíos. Repararlo devuelve un ritmo constante a toda la casa.",
      "Restore the study and its clock.",
      "Віднови кабінет і його годинник.",
      "Restaura el estudio y su reloj.",
      "Study · Quiet focus space",
      "Кабінет · Тихе місце для зосередження",
      "Estudio · Espacio tranquilo para concentrarse"),
    C("The Celebration Room", "Святкова кімната", "La sala de celebraciones",
      "Almost every room is ready. The largest empty space needs lights, a long table, and decorations for the first gathering.",
      "Майже всі кімнати готові. Найбільшому порожньому простору потрібні вогні, довгий стіл і прикраси для першої зустрічі гостей.",
      "Casi todas las habitaciones están listas. El mayor espacio vacío necesita luces, una mesa larga y adornos para la primera reunión.",
      "Finish the celebration room.",
      "Заверши святкову кімнату.",
      "Termina la sala de celebraciones.",
      "Celebration room · Housewarming ready",
      "Святкова кімната · Дім готовий до новосілля",
      "Sala de celebraciones · Lista para la inauguración"),
    C("A House Becomes a Home", "Будинок стає домом", "Una casa se convierte en hogar",
      "Every repaired room now has a purpose. Warm lights fill the windows of the home you restored from the ground up.",
      "Кожна відремонтована кімната тепер має своє призначення. Тепле світло наповнює вікна дому, який ти відновив/відновила з нуля.",
      "Cada habitación reparada tiene ahora un propósito. Luces cálidas llenan las ventanas del hogar que restauraste desde cero.",
      "Open the finished house as a Family Legend.",
      "Відкрий завершений дім як Сімейна легенда.",
      "Abre la casa terminada como Leyenda familiar.",
      "Complete home · Every room restored",
      "Готовий дім · Усі кімнати відновлено",
      "Hogar completo · Todas las habitaciones restauradas"),
  ],
};

// Localized chapter text for one world/level. lang: uk | en | es.
export function chapterText(worldId, level, lang) {
  const list = CHAPTERS[worldId];
  if (!list) return null;
  const c = list[Math.min(10, Math.max(1, level)) - 1];
  const pick = (o) => o[lang] || o.en;
  return {
    title: pick(c.title),
    scene: pick(c.scene),
    mission: pick(c.mission),
    unlock: pick(c.unlock),
  };
}

export function arcText(worldId, lang) {
  const a = ARCS[worldId];
  if (!a) return null;
  const pick = (o) => o[lang] || o.en;
  return {
    title: pick(a.title),
    subtitle: pick(a.subtitle),
    desc: pick(a.desc),
    drop: pick(a.drop),
  };
}
